llokalla-master/HamburgueSisMVC/HamburSisMVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HamburSisMVC.Models;
using BRL;
using Common;

namespace HamburSisMVC.Controllers
{
    public class UsuarioController : Controller
    {
        static List<Telefono> telfe;
        // GET: Usuario
        public ActionResult ListUser()
        {

			//llama a la vita de la lista mandandole la lista recuperada de un modelo
			if (Session["ObjectSession"] != null)
			{
				UsuarioListModel _list = UsuarioListModel.GetUsuarioModelList();
				return View(_list);
			}
			else
				return RedirectToAction("LogIn", "LogIn");
		}
       
        public ActionResult NewUser( )
        {
            CargarCategorias();
            CargarGeneros();
            if(telfe==null)
            telfe = new List<Telefono>();
            UsuarioModel usm = new Models.UsuarioModel();
            Telefonos();
            usm.Phonos = listasConver();
            return View(usm);//abre la vista de nuevo mandando un modelo vacio eso es obligatorio, ta que luego lo recupera pero lleno
        }
      
        [HttpPost]
        public ActionResult NewUser(UsuarioModel usm)//el metodo post de nuevo, los post se deben llamar igual, varia sus parametros, en caso de este pide un modelo
        {
            usm.Phonos = new List<TelefonoModel>();
            try
            {
                
                if (usm.tel.numero == null)
                {
                    // TODO: Add insert logic here
                    Usuario us = new Usuario(usm.userName, usm.password, usm.tipo);//crea un nuevo usuario con los resultados del modelo
                    Persona per = new Persona(usm.persona.nombre, usm.persona.primerAp, usm.persona.segundoAp, usm.persona.fechaNac, usm.persona.direccion, usm.persona.ci, usm.persona.genero);
                    UsuarioBRL.Insert(per, us, telfe);//usa el brl
                    telfe = new List<Telefono>();
                    return RedirectToAction("ListUser");//devuelve a la lista
                }
                else
                {
                    Telefono tel = new Telefono(usm.tel.numero, 1);
                    telfe.Add(tel);
                    usm.Phonos = listasConver();
                    CargarCategorias();
                    CargarGeneros();
                    Telefonos();
                    return View();
                }

            }
            catch
            {
                CargarCategorias();
                CargarGeneros();
                return View();
            }
        }
        // GET: Usuario/Edit/5
        public ActionResult EditUser(int id)// pide un id para recuperar el dato
        {
            CargarCategorias();
            CargarGeneros();
            UsuarioModel us =UsuarioModel.recuperar(id);//modelo que recupera el usuario
            ViewBag.Numeros = us.Phonos;
            return View(us);//llama a su vista cargando el resultado
        }
        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult EditUser(int id,UsuarioModel usm)
        {
            //similar al post de insert
            try
            {
                Usuario us = new Usuario(id, usm.userName, usm.password, usm.activo, usm.tipo, usm.idPersona);
                Persona per = new Persona(usm.persona.idPersona,usm.persona.nombre,usm.persona.primerAp,usm.persona.segundoAp,usm.persona.fechaNac,usm.persona.direccion,usm.persona.ci,usm.persona.genero);
                List<Telefono> tel = new List<Telefono>();
                tel.Add(new Telefono(usm.tel.numero));
                UsuarioBRL.Update(per,us,tel);
                
                return RedirectToAction("ListUser");
            }
            catch
            {
                CargarCategorias();
                CargarGeneros();
                return View();
            }
        }
        // GET: Usuario/Delete/5
        public ActionResult Delete(int id) //contrlador que pide un id, no tiene vista propia
        {
            try
            {
                UsuarioBRL.Delete(id);//borra un usuario
                return RedirectToAction("ListUser");
            }
            catch
            {
                return RedirectToAction("ListUser");
            }
        }
        public void CargarCategorias()
        {
            ViewBag.ListaCategorias = new SelectList(
                           (
                               from t in CategoriaController.CategoriaModel
                               select new SelectListItem
                               {
                                   Text = t.nombre,
                                   Value = t.idCat.ToString()
                               }
                           )
                           , "Value", "Text");
        }
        public void CargarGeneros()
        {
            ViewBag.ListaGenero = new SelectList(
                           (
                               from t in GeneroController.GeneroModel
                               select new SelectListItem
                               {
                                   Text = t.genero,
                                   Value = t.idGen.ToString()
                               }
                           )
                           , "Value", "Text");
        }
        public void Telefonos()
        {
            ViewBag.Numeros = listasConver();
        }
        private List<TelefonoModel> listasConver()
        {
            List<TelefonoModel> res = new List<TelefonoModel>();
            foreach (Telefono item in telfe)
            {
                res.Add(new TelefonoModel { numero = item.Numero, tipo = item.Tipo });
            }
            return res;
        }
	}
}

llokalla-master/HamburgueSisMVC/HamburSisMVC/Views/Usuario/EditUser.cshtml
@model  HamburSisMVC.Models.UsuarioModel
@{
    ViewBag.Title = "EditUser";
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@Resource.Resource.UUser</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.userName)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.userName)
            @Html.ValidationMessageFor(model => model.userName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.tipo)

        </div>
        <div class="editor-field">
           
            @Html.DropDownListFor(model => model.tipo, (IEnumerable<SelectListItem>)ViewBag.ListaCategorias, "--Elejir Categoría--")

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.password)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.password)
            @Html.ValidationMessageFor(model => model.password)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.nombre)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.nombre)
            @Html.ValidationMessageFor(model => model.persona.nombre)

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.primerAp)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.primerAp)
            @Html.ValidationMessageFor(model => model.persona.primerAp)

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.segundoAp)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.segundoAp)
            @Html.ValidationMessageFor(model => model.persona.segundoAp)

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.fechaNac)

        </div>
        <div class="editor-field">

            @Html.EditorFor(model => model.persona.fechaNac)

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.direccion)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.direccion)
            @Html.ValidationMessageFor(model => model.persona.direccion)

        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.ci)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.ci)
            @Html.ValidationMessageFor(model => model.persona.ci)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.genero)

        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.persona.genero, (IEnumerable<SelectListItem>)ViewBag.ListaGenero, "--Elejir Genero--")

        </div>
        <div class="editor-label">
            Telefonos del usuario <br />
            <table>
                <thead>
                    <tr>
                        <td>Numero</td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (HamburSisMVC.Models.TelefonoModel item in ViewBag.Numeros)
                    {
                        <tr>
                            <td>@item.numero</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

        <p>
            <input type="submit" value=@Resource.Resource.Up />
        </p>
    </fieldset>
}

llokalla-master/HamburgueSisMVC/HamburSisMVC/Views/Usuario/ListUser.cshtml
@model IEnumerable<HamburSisMVC.Models.UsuarioModel> 
@{
    ViewBag.Title = "ListUser";
}

<h2>@Resource.Resource.List</h2>
<p>
    @Html.ActionLink(Resource.Resource.New, "../Usuario/NewUser")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idUsuario)<!--  pone de titulo el que tiene el modelo es esa propiedad -->
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
          @Resource.Resource.Delete
        </th>
        <th>
           @Resource.Resource.Update
        </th>

    </tr>

    @foreach (var item in Model)//for del modelo que le llega
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idUsuario)<!--   recuera el dato del modelo -->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
       
            <td>
                @Html.ActionLink(Resource.Resource.Delete, "../Usuario/Delete", new { id = item.idUsuario })<!-- llama a otro metodo del controlador el new es el parametro, se pone nombreparameto=dato; el nombre debe ser el mismo que de el parametro del metodo -->
            </td>
            <td>
                @Html.ActionLink(Resource.Resource.Update, "../Usuario/EditUser", new { id = item.idUsuario })
            </td>

        </tr>
    }

</table>

llokalla-master/HamburgueSisMVC/HamburSisMVC/Views/Usuario/NewUser.cshtml
@model  HamburSisMVC.Models.UsuarioModel
@{
    ViewBag.Title = "NewUser";
}
@using (Html.BeginForm("NewUser", "Usuario", FormMethod.Post, new { }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@Resource.Resource.NewUs</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.userName)<!--  crea un label con el nombre de la prop-->
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.userName)<!--  crea el campo relacionado al modelo asi este ya esta vinculado -->
            @Html.ValidationMessageFor(model => model.userName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.tipo)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.tipo, (IEnumerable<SelectListItem>)ViewBag.ListaCategorias, "--Elejir Categoría--")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.password)
            @Html.ValidationMessageFor(model => model.password)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.nombre)
            @Html.ValidationMessageFor(model => model.persona.nombre)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.primerAp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.primerAp)
            @Html.ValidationMessageFor(model => model.persona.primerAp)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.segundoAp)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.segundoAp)
            @Html.ValidationMessageFor(model => model.persona.segundoAp)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.fechaNac)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.fechaNac)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.direccion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.direccion)
            @Html.ValidationMessageFor(model => model.persona.direccion)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.ci)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.persona.ci)
            @Html.ValidationMessageFor(model => model.persona.ci)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.persona.genero)
        </div>
        <div class="editor-field">

            @Html.DropDownListFor(model => model.persona.genero, (IEnumerable<SelectListItem>)ViewBag.ListaGenero, "--Elejir Genero--")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.tel.numero)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tel.numero)
        </div>
        <div class="editor-label">
           @Resource.Resource.Phones <br />
            <table>
                <thead>
                    <tr>
                        <td>@Resource.Resource.Phone</td>
                    </tr>
                </thead>
                <tbody>
                   
                       @foreach (HamburSisMVC.Models.TelefonoModel item in ViewBag.Numeros)
                       {
                        <tr>
                            <td>@item.numero</td>
                        </tr>
                       }
                    
                </tbody>
            </table>
        </div>
        <p>
            <input type="submit" value=@Resource.Resource.New /><!--  llama al post, recupera solo el modelo-->
        </p>

    </fieldset>
}